### ISSUE TITLE
Should overwrite header Connection with connection-token close.

### ISSUE THREAD

**Issue by markovanderpuil** [eslachance/php-transparent-proxy#4]
This proxy should always return the header Connection: close and not the upstream server Connection header, until it supports keep-alive persistent connections.

**Comment by eslachance** [comment]
I haven't look at the code in a while but isn't that exactly what line 107 does?

```php
fputs($fp, "Connection: close\r\n\r\n");
fputs($fp, $data);
```

**Comment by markovanderpuil** [comment]
That's for the request headers, I suppose I was referring to the response headers since I thought at the time certain upstream webserver configurations could send forced keep-alive connection headers. (I think I actually saw that) But I'm not sure anymore, so you can close this. Thanks for looking into it though.
