### ISSUE TITLE
Has issues with gzip sites

### ISSUE THREAD

**Issue by Zaephor** [eslachance/php-transparent-proxy#5]
Seems to have issues passing gzip sites through. End up with garbage characters, which I believe could be written to a file and decompressed or similar... I've tried artificially removing the gzip tag from 'Accept-Encoding' headers, the result is a variance on the correct page. I'm not sure why, but I keep getting random number/character pairs scattered through the HTML.

**Comment by eslachance** [comment]
I'll take a look at this, seems like I have a hint at least here http://stackoverflow.com/questions/3469040/decoding-gzip-using-php-sockets . Thought it would just pass it as-is.

**Comment by eslachance** [comment]
3a99b972b2411db5eeb7a52c1a84f0edf49f18d8
