### ISSUE TITLE
POST request to URL with GET params

### ISSUE THREAD

**Issue by czjvic** [eslachance/php-transparent-proxy#8]
POST request to url http://www.mysite.com?param=1 will send POST request to url http://www.mysite.com.

Should I send pull request? I extend params of proxy_request to ($url, $getData, $postData, $method)  and handle also getData in request.

**Comment by eslachance** [comment]
If you can do the pull request, yes that'd be great. I haven't taken a look at this code for a while so it helps to refresh my memory a little!

**Comment by eslachance** [comment]
600bce4622b6f0b7f356e1c81b568b842ed11ba2
