### ISSUE TITLE
Can't set double cookie from remote server

### ISSUE THREAD

**Issue by webzhangnan** [eslachance/php-transparent-proxy#9]
```
$expire=60*60*48+time();
$path = "/";
setcookie('ntoken', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', $expire, $path);
setcookie('nkey', 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy', $expire, $path);
```
that remote server set multiple cookie,but receiver just had single cookie.

**Comment by eslachance** [comment]
Hmm, I'm not looking at cooking individually, I'm just sending the headers as-is. I don't recall setting more than one cooking myself but that should work fine.

I'll try a couple of things but that definitely shouldn't be an issue.

**Comment by webzhangnan** [comment]
Sorry, I'm english very bad, php function `setcookie`  will set response header the following
```
Set-Cookie:ntoken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; expires=Sat, 01-Aug-2015 15:25:34 GMT; Max-Age=172800; path=/
```
if you call [header](https://github.com/eslachance/php-transparent-proxy/blob/master/proxy.php#L56) many times `Set-Cookie`, the later  will be replaced previous call.

so you try resolved is by
```
  foreach($headerArray as $headerLine) {
     header($headerLine, FALSE);
    }
```
reference:
http://php.net/manual/en/function.header.php

**Comment by eslachance** [comment]
Well, your english may be imperfect but your description was good. I made the change as you mentionned after checking the reference .Thank you!
In commit d7311dea3905e527c483866de450f368c00c138c
